config:
  credentials: []
  project_repos:
    code-repo.d4science.org/D-Net/dnet-hadoop:
      branch: main
      repo: https://code-repo.d4science.org/D-Net/dnet-hadoop.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ecru-corgi.sh
        container: qc.acc_skimpy-alizarin-caiman
  QC.Doc:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-razzmatazz-moose.sh
        container: qc.doc_stinky-chartreuse-birman
      code-repo.d4science.org/D-Net/dnet-hadoop git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-teal-orangutan.sh
        container: qc.doc_geeky-alizarin-swan
      code-repo.d4science.org/D-Net/dnet-hadoop markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-platinum-starfish.sh
        container: qc.doc_geeky-taupe-dingo
  QC.Lic:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cinnabar-turtle.sh
        container: qc.lic_flimsy-malachite-bloodhound
  QC.Sec:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-charcoal-meerkat.sh
        container: qc.sec_stealthy-copper-lionfish
  QC.Sty:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olivine-akbash.sh
        container: qc.sty_skinny-firebrick-retriever
      code-repo.d4science.org/D-Net/dnet-hadoop flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-tangerine-moose.sh
        container: qc.sty_trippy-olive-zebu
      code-repo.d4science.org/D-Net/dnet-hadoop jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-russet-gopher.sh
        container: qc.sty_snippy-olive-tuatara
  QC.Uni:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-harlequin-dhole.sh
        container: qc.uni_breezy-plum-whale
  QC.Ver:
    repos:
      code-repo.d4science.org/D-Net/dnet-hadoop get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-dandelion-foxhound.sh
        container: qc.ver_lumpy-copper-wolverine
timeout: 5400
